# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-01 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Name')),
                ('Address', models.CharField(max_length=250, verbose_name='Address')),
                ('Profile_Picture', models.ImageField(upload_to='')),
                ('Birthdate', models.DateField(blank=True, null=True)),
                ('Years_of_experience', models.DateField(blank=True, null=True)),
                ('Preferred_Language', models.CharField(max_length=100, verbose_name='Preferred Language')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='application.User'),
        ),
    ]
